---
##Lab 3
##Katrina Ninh
title: Lab 3
subtitle: |
  | Introduction to Health Data Science - PM566
author: "Katrina Ninh"
always_allow_html: true
output: 
  pdf_document:
    latex_engine: xelatex

---


```{r echo=FALSE}

##install.packages("data.table")    # Install & load data.table package
library("data.table")

## Do this once - then comment these lines out to save time
download.file(
  "https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz",
  destfile = file.path("C:\\PM566KatrinaNinh\\met_all.gz"),
  method   = "libcurl",
  timeout  = 60
)

met <- data.table::fread(file.path("C:\\PM566KatrinaNinh\\met_all.gz"))
                         
## ----------- Step 2: Check the dimensions, headers, footers. How many columns, rows are there?  -------

dim(met)
##[1] 2377343      30

head(met)

## ------------------------------- Step 3: Take a look at the variables --------------------------------

str(met)

## ------------------------------- Step 4: Take a closer look at the key variables ----------------------

table(met$year)

table(met$day)

table(met$hour)

summary(met$temp)

summary(met$elev)

summary(met$wind.sp)


met[met$elev==9999.0] <- NA
summary(met$elev)

met <- met[temp>-40]
met2 <- met[order(temp)]
head(met2)
summary(met2$temp)

##We again notice that there is a -17.2C temperature reading that seems suspicious.

## -------------- Step 5: Check the data against an external data source -------------------

met <- met[temp>-15]
met2 <- met[order(temp)]
head(met2)
summary(met2$temp)


## ------------------------- Step 6 : Calculate summary statistics ------------------------

elev <- met[elev==max(elev), ]
summary(elev)

cor(elev$temp, elev$wind.sp, use="complete")
## [1] -0.09373843
cor(elev$temp, elev$hour, use="complete")
## [1] 0.4397261
cor(elev$wind.sp, elev$day, use="complete")
## [1] 0.3643079
cor(elev$wind.sp, elev$hour, use="complete")
## [1] 0.08807315
cor(elev$temp, elev$day, use="complete")
## [1] -0.003857766


## -------------- Step 7 : Exploratory graphs --------------------------------

hist(met$elev, breaks=100)
## See graph in RStudio

hist(met$temp)
## See graph in RStudio

hist(met$wind.sp)
## See graph in RStudio

##install.packages("leaflet")
library(leaflet)
library(stringr)

##install.packages("sp")
library(sp)

##install.packages("maps")
library(maps)


leaflet(elev) %>%
  addProviderTiles('OpenStreetMap') %>% 
  addCircles(lat=~lat,lng=~lon, opacity=1, fillOpacity=1, radius=100)

##install.packages("lubridate")    
library(lubridate)
elev$date <- with(elev, ymd_h(paste(year, month, day, hour, sep= ' ')))
summary(elev$date)

elev <- elev[order(date)]
head(elev)


##With the date-time variable we can plot the time series of temperature and wind speed.

plot(elev$date, elev$temp, type='l')

plot(elev$date, elev$wind.sp, type='l')


##Summary

## For the temperature:
## - The temperature is cooler in the evening/morning and heats up during the day
## - Temperature range is smaller at the beginning of August and late August and higher mid August.

## For the Wind:
## - Wind speed varies throughout the day
## - Wind speed range is also smaller at the beginning of August and late August and higher mid August

